version: '3'

services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      DATABASE_HOST: db
    env_file:
      - ./.env
    ports:
      - 8080:8080
    networks:
      - wedcam
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    container_name: wedcam-psql
    restart: always
    volumes:
      - wedcam-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=wedcam-postgres
      - POSTGRES_DB=wedcam
    ports:
      - 7482:5432
    networks:
      - wedcam
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  wedcam-db-data:

networks:
  wedcam:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          ip_range: 172.28.5.0/24
